name: Run Stack Compatibility Test

on:
  repository_dispatch:
    types: StackCompatibilityTest
      
jobs:
  stackTest:
    env:
      GRADLE_ARGS: -Partifactory_user=${{secrets.ARTIFACTORY_USER}} -Partifactory_password=${{secrets.ARTIFACTORY_TOKEN}}
    name: Stack compatibility test for service:${{ github.event.client_payload.service }} version:${{ github.event.client_payload.version }} pluginSha:${{ github.event.client_payload.sha }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}
      - name: set up java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: run tests
        id: run_tests
        uses: armory-io/plugin-test-runner@stack
        with: 
          service: ${{ github.event.client_payload.service }}
          version: ${{ github.event.client_payload.version }}
          plugin_sha: ${{ github.event.client_payload.sha }}
      - name: handle missing fingerprint
        uses: technote-space/workflow-conclusion-action@v2
        if: ${{ steps.run_tests.outputs.TEST_OUTCOME }} == 'noFingerprint'
        with:
          status: action_required

